### Signup
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "securepassword"
}
### Login
POST http://127.0.0.1:8000/login
Content-Type: application/x-www-form-urlencoded

username=user1@example.com&password=securepassword
### Protected Route (Replace <TOKEN>)
GET http://127.0.0.1:8000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyMzU3MzI2fQ.yMTzsFY3VH9vlNzF1qoT-JAqLv9KvetLUwvVDsXHEuo

### Circular Route
POST http://127.0.0.1:8000/circulars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQyMzU3MzI2fQ.yMTzsFY3VH9vlNzF1qoT-JAqLv9KvetLUwvVDsXHEuo
Content-Type: application/json

{
  "title": "Math Tutor Needed"
}

username=user@example.com&password=securepassword
### Protected Route (Replace <TOKEN>)
GET http://127.0.0.1:8000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0MjM1NzYyOH0.7vme1IblwdC1LAZ1t6idlSpt8qw_ocRdYPnDdyNMMLQ

### Circular Route
POST http://127.0.0.1:8000/circulars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImV4cCI6MTc0MjM1NzYyOH0.7vme1IblwdC1LAZ1t6idlSpt8qw_ocRdYPnDdyNMMLQ
Content-Type: application/json

{
  "title": "Math Tutor Needed"
}
